---
title: "Health Data"
author: "Jessie Midgley"
date: "11/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(tidyr)
library(readr)
library(dplyr)
library(stringr)
library(tibble)
library(RSQLite)
library(DBI)
```


```{r import data}
Health <- read.csv("Big_Cities_Health_Data_Inventory.csv")
```



```{r indicators table}
# create Indicator ID
indicators <- unique(Health[,1:2]) %>% 
  mutate(Indicator_ID = row_number()) %>% 
  select(Indicator_ID, Indicator.Category, Indicator)

Health$Indicator_ID <- cumsum(!duplicated(Health[,1:2]))
```

```{r places table}
# separate Place column and add ID
places <- Health %>% separate(Place, into=c("City", "State"), sep=",", fill = "left")
places <- unique(select(places, State, City)) %>% 
  mutate(Place_ID = row_number()) %>%
  select(Place_ID, City, State)

Health$Place_ID <- cumsum(!duplicated(Health[,7]))
```

```{r years table}
#separate Year column and add ID
years <- Health %>% separate(Year, into=c("Start.Year", "End.Year"), sep="-", fill = "right")
years <- unique(select(years, Start.Year, End.Year)) %>% 
  mutate(Year_ID = row_number()) %>%
  select(Year_ID, Start.Year, End.Year)

Health$Year_ID <- cumsum(!duplicated(Health[,3]))
```

```{r bchc table}
# clean up BCHC Methodologies
Health$BCHC.Requested.Methodology = stringr::str_remove(Health$BCHC.Requested.Methodology, "\\.$") 
Health$BCHC.Requested.Methodology = str_squish(Health$BCHC.Requested.Methodology)
Health$BCHC.Requested.Methodology = gsub("20014", "2014", Health$BCHC.Requested.Methodology)
Health <- Health %>% mutate_all(na_if,"")

# extract column from main table 
bchc <- as_tibble(unique(Health[,8]), )
bchc <- rename(bchc, "BCHC.Requested.Methodology" = value)
# get bchc years
bchc <- bchc %>% 
  mutate(BCHC_years = str_extract(BCHC.Requested.Methodology, "(([0-9]{4}, )*[0-9]{4})"))
# create bchc ID           
bchc <- bchc %>% mutate(BCHC_ID = row_number())
# ICD-10 codes
bchc <- bchc %>% 
  separate(BCHC.Requested.Methodology, into=c("BCHC.Requested.Methodology", "ICD-10.values"), 
           sep="ICD-10 Codes: ", fill="right")
# crude vs adjusted
crude <- str_extract(bchc$BCHC.Requested.Methodology, "crude rate per 100,000")
adjusted <- str_extract(bchc$BCHC.Requested.Methodology, "age adjusted to the year")
bchc$crude <- crude
bchc$adjusted <- adjusted
bchc <- bchc %>% mutate(crude.vs.adjusted = coalesce(crude,adjusted)) %>%
  select(BCHC_ID, BCHC.Requested.Methodology, 'ICD-10.values', BCHC_years, crude.vs.adjusted)
rm(crude, adjusted)  

Health$BCHC_ID <- cumsum(!duplicated(Health[,8]))
```

```{r sources table}
# create Source ID
sources <- unique(Health[9]) %>% 
  mutate(Source_ID = row_number()) %>%
  select(Source_ID, Source)

Health$Source_ID <- cumsum(!duplicated(Health[,9]))
```

```{r methods table}
# create Methods ID
methods <- unique(Health[,10:11]) %>% 
  mutate(Method_ID = row_number()) %>%
  select(Method_ID, Methods, Notes)

Health$Method_ID <- cumsum(!duplicated(Health[,10:11]))
```

```{r demographics table}
demographics <- unique(Health[,4:5]) %>% 
  mutate(Demographic_ID = row_number()) %>%
  select(Demographic_ID, Gender, Race..Ethnicity)

Health$Demographic_ID <- cumsum(!duplicated(Health[,4:5]))
```

```{r main table}
maintable <- Health %>% 
  select(Value, Indicator_ID, Year_ID, Demographic_ID, Place_ID, BCHC_ID, Source_ID, Method_ID)
```


```{r connect to SQLite}
conn <- dbConnect(RSQLite::SQLite(), "health.db")
```

```{r make schema}
dbSendQuery(conn,
       "CREATE TABLE Indicators
       (Indicator_ID INT PRIMARY KEY,
        [Indicator.Category] VARCHAR(100),
        Indicator VARCHAR(250))")

dbSendQuery(conn,
       "CREATE TABLE Years
       (Year_ID INT PRIMARY KEY,
        [Start.Year] INT,
        [End.Year] INT)")

dbSendQuery(conn,
       "CREATE TABLE Demographics
       (Demographic_ID INT PRIMARY KEY,
        Gender VARCHAR(10),
        [Race..Ethnicity] VARCHAR(50))")

dbSendQuery(conn,
       "CREATE TABLE Places
       (Place_ID INT PRIMARY KEY,
        City VARCHAR(30),
        State VARCHAR(15))")

dbSendQuery(conn,
       "CREATE TABLE BCHC_Requested_Methodology
       (BCHC_ID INT PRIMARY KEY,
        [BCHC.Requested.Methodology] TEXT,
        [ICD-10.values] VARCHAR(100),
        BCHC_years VARCHAR(20),
        [crude.vs.adjusted] VARCHAR(30))")

dbSendQuery(conn,
       "CREATE TABLE Sources
       (Source_ID INT PRIMARY KEY,
        Source TEXT)")

dbSendQuery(conn,
       "CREATE TABLE Methods
       (Method_ID INT PRIMARY KEY,
        Methods TEXT,
        Notes VARCHAR(250))")

dbSendQuery(conn,
       "CREATE TABLE Main_Table
       (Value FLOAT,
       Indicator_ID INT, 
       Year_ID INT, 
       Demographic_ID INT, 
       Place_ID INT, 
       BCHC_ID INT, 
       Source_ID INT, 
       Method_ID INT,
       FOREIGN KEY(Indicator_ID) REFERENCES Indicators(Indicator_ID) ON UPDATE CASCADE,
       FOREIGN KEY(Year_ID) REFERENCES Years(Year_ID) ON UPDATE CASCADE,
       FOREIGN KEY(Demographic_ID) REFERENCES Demographics(Demographic_ID) ON UPDATE CASCADE,
       FOREIGN KEY(Place_ID) REFERENCES Places(Place_ID) ON UPDATE CASCADE,
       FOREIGN KEY(BCHC_ID) REFERENCES BCHC_Requested_Methodology(BCHC_ID) ON UPDATE CASCADE,
       FOREIGN KEY(Source_ID) REFERENCES Sources(Source_ID) ON UPDATE CASCADE,
       FOREIGN KEY(Method_ID) REFERENCES Methods(Method_ID) ON UPDATE CASCADE)")

```


```{r insert data into schema}
dbAppendTable(conn, "Indicators", indicators)
dbAppendTable(conn, "Years", years)
dbAppendTable(conn, "Demographics", demographics)
dbAppendTable(conn, "Places", places)
dbAppendTable(conn, "BCHC_Requested_Methodology", bchc)
dbAppendTable(conn, "Sources", sources)
dbAppendTable(conn, "Methods", methods)
dbAppendTable(conn, "Main_Table", maintable)

dbGetQuery(conn, "SELECT * FROM Sources" )
```

```{r joins}
dbGetQuery(conn, "SELECT * FROM  Indicators LEFT JOIN Main_Table on Indicators.Indicator_ID = Main_Table.Indicator_ID")
dbGetQuery(conn, "SELECT * FROM  Years LEFT JOIN Main_Table on Years.Year_ID = Main_Table.Year_ID")
dbGetQuery(conn, "SELECT * FROM  Demographics LEFT JOIN Main_Table on Demographics.Demographic_ID = Main_Table.Demographic_ID")
dbGetQuery(conn, "SELECT * FROM  Places LEFT JOIN Main_Table on Places.Place_ID = Main_Table.Place_ID")
dbGetQuery(conn, "SELECT * FROM  BCHC_Requested_Methodology LEFT JOIN Main_Table on BCHC_Requested_Methodology.BCHC_ID = Main_Table.BCHC_ID")
dbGetQuery(conn, "SELECT * FROM  Sources LEFT JOIN Main_Table on Sources.Source_ID = Main_Table.Source_ID")
dbGetQuery(conn, "SELECT * FROM  Methods LEFT JOIN Main_Table on Methods.Method_ID = Main_Table.Method_ID")
```

